name: Deploy on AWS lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: |
          go mod download
      - name: Build
        run: |
          make build
      - name: Zip binary
        run: |
          make zip
      - name: Deploy to Lambda
        uses: appleboy/aws-lambda-action@v0.1.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: sa-east-1
          function_name: fin-app-cron
          zip_file: main.zip
